setwd("C:\\Users\\MARK\\Desktop\\Marwin Documents\\Coursera Courses\\4. Exploratory Data Analysis\\Week 1\\Course Project 1")

library(dplyr)
library(lubridate)

data<-read.table("./household_power_consumption.txt",sep=";")
head(data,n=6)

#Subsetting Data & Cleaning Data
head(data$V1)
head(dmy(data$V1))
which(dmy(data$V1)=="2007-02-01")
which(dmy(data$V1)=="2007-02-02")

dat<-data[66638:69517,]
head(dat)
tail(dat)
names(dat)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
rownames(dat)<-c(1:2880)
head(dat)
tail(dat)

#Plotting
gap<-as.numeric(as.character(dat$Global_active_power))
par(mfrow=c(2,2))
plot(c(1:2880),gap,type="l",ylab="Global Active Power",xlab="Days",xaxt="n")
axis(side=1, at=0, labels ="Thu")
axis(side=1,at=1440,labels="Fri")
axis(side=1, at=2880, labels ="Sat")
vol<-as.numeric(as.character(dat$Voltage))
plot(c(1:2880),vol,type="l",ylab="Voltage",xlab="daytime",xaxt="n")
axis(side=1, at=0, labels ="Thu")
axis(side=1,at=1440,labels="Fri")
axis(side=1, at=2880, labels ="Sat")
sub1<-as.numeric(as.character(dat$Sub_metering_1))
sub2<-as.numeric(as.character(dat$Sub_metering_2))
sub3<-as.numeric(as.character(dat$Sub_metering_3))
plot(c(1:2880),sub1,type="l",ylab="Energy sub metering",xlab="Days",xaxt="n",col="black",ylim=c(0,40))
lines(c(1:2880),sub2,type="l",xaxt="n",col="red")
lines(c(1:2880),sub3,type="l",xaxt="n",col="blue")
axis(side=1, at=0, labels ="Thu")
axis(side=1,at=1440,labels="Fri")
axis(side=1, at=2880, labels ="Sat")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=1)
grp<-as.numeric(as.character(dat$Global_reactive_power))
plot(c(1:2880),grp,type="l",ylab="Global_reactive_power",xlab="daytime",xaxt="n")
axis(side=1, at=0, labels ="Thu")
axis(side=1,at=1440,labels="Fri")
axis(side=1, at=2880, labels ="Sat")
dev.copy(png,file="Plot4.png")
dev.off()
